-- MySQL Script generated by MySQL Workbench
-- Mon May 18 15:33:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema precode
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `precode` ;

-- -----------------------------------------------------
-- Schema precode
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `precode` DEFAULT CHARACTER SET utf8 ;
USE `precode` ;

-- -----------------------------------------------------
-- Table `precode`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `precode`.`categoria` ;

CREATE TABLE IF NOT EXISTS `precode`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCategoriaPai` INT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fbk1_categoria_idx` (`idCategoriaPai` ASC) ,
  CONSTRAINT `fbk1_categoria`
    FOREIGN KEY (`idCategoriaPai`)
    REFERENCES `precode`.`categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `precode`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `precode`.`produto` ;

CREATE TABLE IF NOT EXISTS `precode`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(130) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 0,
  `urlFotoProduto` VARCHAR(45) NULL,
  `quantidade` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fbk1_produto_idx` (`idCategoria` ASC) ,
  CONSTRAINT `fbk1_produto`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `precode`.`categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `precode`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `precode`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `precode`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subTotal` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `valorFrete` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `total` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `precode`.`produtoCarrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `precode`.`produtoCarrinho` ;

CREATE TABLE IF NOT EXISTS `precode`.`produtoCarrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProduto` INT NOT NULL,
  `idCarrinho` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fbk1_produtoCarrinho_idx` (`idProduto` ASC) ,
  INDEX `fbk1_produtoCarrinho_idx1` (`idCarrinho` ASC) ,
  CONSTRAINT `fbk1_produtoCarrinho`
    FOREIGN KEY (`idProduto`)
    REFERENCES `precode`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fbk2_produtoCarrinho`
    FOREIGN KEY (`idCarrinho`)
    REFERENCES `precode`.`carrinho` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
